Get unique recipe - Endpoint
Chris-DevSeal/devcraft-recipe-frontend pull request #22
Opened 2024-06-09 10:44 UTC by ViliaZ

2024-06-09 20:05 UTC, Chris-DevSeal requested changes

2024-06-09 20:05 UTC, Chris-DevSeal commented on src/utils/RecipeService.ts
> + async loadRecipeById(id: number): Promise<Recipe | null> {
Ich denke nicht, dass hier ein Promise returned wird - durch das await, wird das Promise zu einem Recipe resolved (?) @ViliaZ

2024-06-10 04:59 UTC, ViliaZ commented on src/utils/RecipeService.ts
> + async loadRecipeById(id: number): Promise<Recipe | null> {
Das sind promises, weil sie auf den prismaClient zurückgehen und die function darauf warten muss

2024-06-10 07:23 UTC, Chris-DevSeal commented on src/utils/RecipeService.ts
> + async loadRecipeById(id: number): Promise<Recipe | null> {
Ah okay, danke für die erklärung tiptop 👍

2024-06-10 07:24 UTC, merged