Add endpoint to create a new recipe
Chris-DevSeal/devcraft-recipe-frontend pull request #23
Opened 2024-06-09 10:56 UTC by ViliaZ

- further ToDos: add frontend request to the apt

2024-06-09 20:17 UTC, Chris-DevSeal requested changes

2024-06-09 20:17 UTC, Chris-DevSeal commented on src/app/api/recipes/[id]/route.ts
Unabsichtlich mit gepusht? - das ist doch von pr #22 (?) @ViliaZ

2024-06-09 20:17 UTC, Chris-DevSeal commented on src/utils/RecipeService.ts
> +  ): Promise<Recipe> {
auch hier wird doch das promise resolved & somit nicht returned oder @ViliaZ (?)

2024-06-09 20:17 UTC, Chris-DevSeal commented on src/utils/RecipeService.ts
> +  async loadRecipeById(id: number): Promise<Recipe | null> {
Dieser Teil gehört auch zu #22 oder @ViliaZ (?)

2024-06-10 05:00 UTC, ViliaZ commented on src/utils/RecipeService.ts
> +  ): Promise<Recipe> {
@Chris-DevSeal  siehe mein Kommentar bei #22. Das ist ein Promise wegen prismaClient

2024-06-10 05:04 UTC, ViliaZ commented on src/app/api/recipes/[id]/route.ts
danke, ich weiss gerade nicht wie das zustande gekommen ist.

2024-06-10 05:04 UTC, ViliaZ commented on src/utils/RecipeService.ts
> +  async loadRecipeById(id: number): Promise<Recipe | null> {
siehe oben

2024-06-10 07:25 UTC, Chris-DevSeal commented on src/utils/RecipeService.ts
> +  ): Promise<Recipe> {
👍 alright, danke für die Erklärung 💯

2024-06-10 07:26 UTC, Chris-DevSeal commented on src/app/api/recipes/[id]/route.ts
Ich auch nicht, möchtest du dir gemeinsam ansehen, wie wir das beheben oder hast du schon eine Idee @ViliaZ ?

2024-06-10 07:52 UTC, ViliaZ commented on src/app/api/recipes/[id]/route.ts
@Chris-DevSeal hier ist tatsächlich einfach der commit vom #22 mit gepusht worden, weil ich den feature branch vor dem commit erstellt habe. Hm... Also entweder ich erstelle einen neuen Pull request und lösche diesen oder du mergest den in main. Das wären so meine Ideen (ich hatte den Fall noch nicht, dass ich einen Merge Request bearbeitet habe)...

2024-06-10 08:22 UTC, Chris-DevSeal commented on src/app/api/recipes/[id]/route.ts
Habs deleted @ViliaZ

2024-06-10 08:22 UTC, Chris-DevSeal approved these changes

2024-06-10 08:47 UTC, merged